In [10]:
from vizdoom import *
import random
import numpy as np
import time

In [12]:
game = DoomGame()
game.load_config("deathmatch.cfg")
game.init()
actions= np.identity(23, dtype=np.uint8) # modify this
episodes = 10
for epsisode in range(episodes):
    game.new_episode()
    while not game.is_episode_finished():
        state = game.get_state()
        img = state.screen_buffer
        info= state.game_variables
        reward = game.make_action(random.choice(actions))
        print(random.choice(actions), reward, info)
        time.sleep(0.01)
    print("Result:", game.get_total_reward())
    time.sleep(1.5)

[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0] 0.0 [  0. 100.   0.   1.   0.]
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   1.   0.]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   1.   0.]
[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 0.0 [  0. 100.   0.   2.  50.]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0] 0.0 

ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.